### ISSUE TITLE
Error reading @id when mapping to map object

### ISSUE THREAD

**Issue by miggy9001** [jsog/jsog-jackson#12] opened 2016-09-15 18:49 UTC
When using the default Jackson generator 'JSOGGenerator' and default resolver 'SimpleObjectIdResolver' there is a defect with resolving java.utilsmap objects. So in java I make a map that contains the following '{ keyA: objA, keyB: objB }' and it gets mapped to JSON with no @ID as: 
'{keyA: { @id: 1, key1: valA, Key2: val1 }, keyB: { @id: 2, key1: valB, key2: val2 } }'. Now I take this JSON into a scripting language such as Ruby or JavaScript that has no idea it was a map but can resolve the @ids so I can make changes. The issue comes in when I regenerate it to be sent back becasue it will put an @id on the JSON such as this '{ @id: 1, { @id: 2, key1: valC, Key2: val3 }, { @id: 3, key1: valD, key2: val4 } }'. And this will throw a forward reference error because the id is present. Jackson should be able to handle this case becasue Ruby and Javascript have no way to tell this object is a map and the outputted JSON is valid for an object.

**Comment by peidong-hu** [comment] 2017-04-28 01:58
Yes. I have the exact same problem in my project. I was trying to hack the spring map deserializer on server side. But failed to do so in past 2 days.

**Comment by stickfigure** [comment] 2017-04-28 04:10
Interesting, Map isn't getting assigned an id. This sounds like a Jackson issue - a question for @cowtowncoder perhaps.

**Comment by cowtowncoder** [comment] 2017-04-28 04:14
Needless to say, actual reproduction (ideally in form of unit test) would be needed. Textual description leaves out all important details like actual classes, how code is invoked, versions involved.

**Comment by peidong-hu** [comment] 2017-04-28 15:50
Yes. the problem is in jsog js library, https://github.com/jsog/jsog/blob/master/lib/JSOG.js

Just look at the js source code at line, https://github.com/jsog/jsog/blob/master/lib/JSOG.js#L76 , the js lib add id into every js array type, which could be a Map type in java jackson.  

I was trying to mixin or intercept into MapDeserializer. But it seems that there is no way to intercept Jackson MapDeserializer, I couldn't find the code which is taking mixin or any interceptor. All my experiments were failed.

BeanDeserializer does have them. And I could easily mixin or intercept it.

**Comment by stickfigure** [comment] 2017-04-28 17:05
> the problem is in jsog js library

Nonsense. This is the expected behavior of a JSOG stream; objects receive ids and repeated references are turned into refs.

If I understand this correctly, it sounds like Jackson's id/ref deserialization process is having trouble when deserializing to Map objects? As Tatu said: Can you create a test case for this? That's the first step. Perhaps it is a language issue but it's very hard to read and understand the issue from the description. A test case will resolve the ambiguity.

**Comment by peidong-hu** [comment] 2017-05-03 15:34
Agree that my saying 'the problem is in jsog js lib' is not the right way to express the issue we have. Let me lay out this example to express it,

let's say we have a js map membered with arrays,
var arraysMap = {"mem1":[object1, object2, object3], "mem2":[obj1, obj2,obj3]};
var jsogEncodedArraysMap = JSOG.encode(arraysMap);
if we print jsogEncodedArraysMap, it will look something like this,
{
"@id": "1",
"mem1":[object1, object2, object3],
"mem2":[obj1, obj2, obj3]
}

On the server side, we define the rest request mapping parameter as
public Map<String, List<Object>> acceptRequst(Map<String, List<Object>>) {
}

In this case, Jackson on server will raise the exception that it can't map the value of "@id" to an Array since it is a string type.

**Comment by cowtowncoder** [comment] 2017-05-03 19:41
Object Ids are not really usable for `List`s or `Map`s, but POJOs. So although such POJOs may be included in `List`s, `Map`s and arrays, those container types themselves will not work well (if at all) with Object Ids.

It is usually possible to create "Map-like" POJOs by use of `@JsonAnyGetter` / `@JsonAnySetter`: you may define set of static (fixed) properties, but then allow any other properties as well.

**Comment by stickfigure** [comment] 2017-05-03 20:00
I agree that `List`s don't make much sense, but why not `Map`s? It's just an arbitrary mapping of a JSON object, no?

**Comment by cowtowncoder** [comment] 2017-05-03 20:16
@stickfigure It's more of a technical problem than semantical: I agree that shared references would make sense for many or all structured types. So it is not prevent due to not making sense: rather it couldn't be implemented as part of POJO reference handling.
It could/should be filed as an improvement idea.

**Comment by f0def** [comment] 2017-07-06 08:34
@miggy8234 @peidong-hu met with this problem, managed to get around?

**Comment by peidong-hu** [comment] 2017-07-07 00:41
I have to iterate the objects inside of the map to encode and decode.

**Comment by f0def** [comment] 2017-07-21 05:23
I use jackson-databind 2.8.3
May be some one will come in handy, I manager this like:

create `MixIn` for the `Map`
```java
@JsonIgnoreProperties(value = {"@id"})
public abstract class JsogMapMixIn {
}
```

Make modification of `com.fasterxml.jackson.databind.deser.std.MapDeserializer`. I think it's a mistake in the protected final method `MapDeserializer#_readAndBind(JsonParser, DeserializationContext, Map)`. 
**Ignoring should be before attempting to parse.**
Change the part 
```java
        for (; keyStr != null; keyStr = p.nextFieldName()) {
            Object key = keyDes.deserializeKey(keyStr, ctxt);
            // And then the value...
            JsonToken t = p.nextToken();
            if (_ignorableProperties != null && _ignorableProperties.contains(keyStr)) {
                p.skipChildren();
                continue;
            }
          ....
       }
```
to 

```java
    for (; keyStr != null; keyStr = p.nextFieldName()) {
      if (_ignorableProperties != null && _ignorableProperties.contains(keyStr)) {
        JsonToken t = p.nextToken();
        p.skipChildren();
        continue;
      }
      Object key = keyDes.deserializeKey(keyStr, ctxt);
     ...
    }
```

To do this I had to completely copy and extend `MapDeserializer` because you use `protected final` modificator 😢 , so:

```java
/**
 * Copied from {@link MapDeserializer}.
 */
public class JsogMapDeserializer extends MapDeserializer {

  public JsogMapDeserializer(MapDeserializer src) {
    super(src);
  }

  private JsogMapDeserializer(MapDeserializer src, KeyDeserializer keyDeser, JsonDeserializer<Object> valueDeser,
                              TypeDeserializer valueTypeDeser, Set<String> ignorable) {
    super(src, keyDeser, valueDeser, valueTypeDeser, ignorable);
  }

  @Override
  protected MapDeserializer withResolved(KeyDeserializer keyDeser, TypeDeserializer valueTypeDeser,
                                         JsonDeserializer<?> valueDeser, Set<String> ignorable) {
    if (_keyDeserializer == keyDeser &&
      _valueDeserializer == valueDeser &&
      _valueTypeDeserializer == valueTypeDeser &&
      _ignorableProperties == ignorable) {
      return this;
    }
    return new JsogMapDeserializer(this,
      keyDeser, (JsonDeserializer<Object>) valueDeser, valueTypeDeser, ignorable);
  }

  @SuppressWarnings("unchecked")
  @Override
  public Map<Object, Object> deserialize(JsonParser p, DeserializationContext ctxt) throws IOException {
    if (_propertyBasedCreator != null) {
      return _deserializeUsingCreator(p, ctxt);
    }
    if (_delegateDeserializer != null) {
      return (Map<Object, Object>) _valueInstantiator.createUsingDelegate(ctxt,
        _delegateDeserializer.deserialize(p, ctxt));
    }
    if (!_hasDefaultCreator) {
      return (Map<Object, Object>) ctxt.handleMissingInstantiator(getMapClass(), p,
        "no default constructor found");
    }
    // Ok: must point to START_OBJECT, FIELD_NAME or END_OBJECT
    JsonToken t = p.getCurrentToken();
    if (t != JsonToken.START_OBJECT && t != JsonToken.FIELD_NAME && t != JsonToken.END_OBJECT) {
      // (empty) String may be ok however:
      if (t == JsonToken.VALUE_STRING) {
        return (Map<Object, Object>) _valueInstantiator.createFromString(ctxt, p.getText());
      }
      // slightly redundant (since String was passed above), but
      return _deserializeFromEmpty(p, ctxt);
    }
    final Map<Object, Object> result = (Map<Object, Object>) _valueInstantiator.createUsingDefault(ctxt);
    if (_standardStringKey) {
      _readAndBindStringKeyMap(p, ctxt, result);
      return result;
    }
    readAndBind(p, ctxt, result);
    return result;
  }

  /**
   * Fixed version of {@link #_readAndBind(JsonParser, DeserializationContext, Map)}.
   */
  protected void readAndBind(JsonParser p, DeserializationContext ctxt,
                             Map<Object, Object> result) throws IOException {
    final KeyDeserializer keyDes = _keyDeserializer;
    final JsonDeserializer<Object> valueDes = _valueDeserializer;
    final TypeDeserializer typeDeser = _valueTypeDeserializer;

    MapReferringAccumulator referringAccumulator = null;
    boolean useObjectId = valueDes.getObjectIdReader() != null;
    if (useObjectId) {
      referringAccumulator = new MapReferringAccumulator(_mapType.getContentType().getRawClass(), result);
    }

    String keyStr;
    if (p.isExpectedStartObjectToken()) {
      keyStr = p.nextFieldName();
    } else {
      JsonToken t = p.getCurrentToken();
      if (t == JsonToken.END_OBJECT) {
        return;
      }
      if (t != JsonToken.FIELD_NAME) {
        ctxt.reportWrongTokenException(p, JsonToken.FIELD_NAME, null);
      }
      keyStr = p.getCurrentName();
    }

    for (; keyStr != null; keyStr = p.nextFieldName()) {
      if (_ignorableProperties != null && _ignorableProperties.contains(keyStr)) {
        JsonToken t = p.nextToken();
        p.skipChildren();
        continue;
      }
      Object key = keyDes.deserializeKey(keyStr, ctxt);
      // And then the value...
      JsonToken t = p.nextToken();
      try {
        // Note: must handle null explicitly here; value deserializers won't
        Object value;
        if (t == JsonToken.VALUE_NULL) {
          value = valueDes.getNullValue(ctxt);
        } else if (typeDeser == null) {
          value = valueDes.deserialize(p, ctxt);
        } else {
          value = valueDes.deserializeWithType(p, ctxt, typeDeser);
        }
        if (useObjectId) {
          referringAccumulator.put(key, value);
        } else {
          result.put(key, value);
        }
      } catch (UnresolvedForwardReference reference) {
        handleUnresolvedReference(p, referringAccumulator, key, reference);
      } catch (Exception e) {
        wrapAndThrow(e, result, keyStr);
      }
    }
  }

  protected void handleUnresolvedReference(JsonParser jp, MapReferringAccumulator accumulator,
                                           Object key, UnresolvedForwardReference reference) throws
    JsonMappingException {
    if (accumulator == null) {
      throw JsonMappingException.from(jp, "Unresolved forward reference but no identity info.", reference);
    }
    ReadableObjectId.Referring referring = accumulator.handleUnresolvedReference(reference, key);
    reference.getRoid().appendReferring(referring);
  }

  public static class MapReferringAccumulator {
    private final Class<?> valueType;
    private Map<Object, Object> result;
    /**
     * A list of {@link MapReferring} to maintain ordering.
     */
    private List<MapReferring> accumulator = new ArrayList<>();

    public MapReferringAccumulator(Class<?> valueType, Map<Object, Object> result) {
      this.valueType = valueType;
      this.result = result;
    }

    /**
     * put.
     */
    public void put(Object key, Object value) {
      if (accumulator.isEmpty()) {
        result.put(key, value);
      } else {
        MapReferring ref = accumulator.get(accumulator.size() - 1);
        ref.next.put(key, value);
      }
    }

    /**
     * handleUnresolvedReference.
     */
    public ReadableObjectId.Referring handleUnresolvedReference(UnresolvedForwardReference reference, Object key) {
      MapReferring id = new MapReferring(this, reference, valueType, key);
      accumulator.add(id);
      return id;
    }

    /**
     * resolveForwardReference.
     */
    public void resolveForwardReference(Object id, Object value) throws IOException {
      Iterator<MapReferring> iterator = accumulator.iterator();
      // Resolve ordering after resolution of an id. This means either:
      // 1- adding to the result map in case of the first unresolved id.
      // 2- merge the content of the resolved id with its previous unresolved id.
      Map<Object, Object> previous = result;
      while (iterator.hasNext()) {
        MapReferring ref = iterator.next();
        if (ref.hasId(id)) {
          iterator.remove();
          previous.put(ref.key, value);
          previous.putAll(ref.next);
          return;
        }
        previous = ref.next;
      }

      throw new IllegalArgumentException("Trying to resolve a forward reference with id [" + id +
        "] that wasn't previously seen as unresolved.");
    }
  }

  public static class MapReferring extends ReadableObjectId.Referring {
    private final JsogMapDeserializer.MapReferringAccumulator parent;

    public final Map<Object, Object> next = new LinkedHashMap<>();
    public final Object key;

    MapReferring(JsogMapDeserializer.MapReferringAccumulator parent, UnresolvedForwardReference ref,
                 Class<?> valueType, Object key) {
      super(ref, valueType);
      this.parent = parent;
      this.key = key;
    }

    @Override
    public void handleResolvedForwardReference(Object id, Object value) throws IOException {
      parent.resolveForwardReference(id, value);
    }
  }
}
```

And last I create `JsogModule` and register in Object Mapper `objectMapper.registerModule(new JsogModule());`

```java
public class JsogModule extends SimpleModule {

  public JsogModule() {
  }

  @Override
  public void setupModule(SetupContext context) {
    context.setMixInAnnotations(Map.class, JsogMapMixIn.class);
    context.addBeanDeserializerModifier(new BeanDeserializerModifier() {
      @Override
      public JsonDeserializer<?> modifyMapDeserializer(DeserializationConfig config, MapType type,
                                                       BeanDescription beanDesc, JsonDeserializer<?> deserializer) {
        return new JsogMapDeserializer((MapDeserializer) deserializer);
      }
    });
  }
}
```

**Comment by stickfigure** [comment] 2018-11-05 17:49
Closing this since it doesn't appear to be something we can address in jsog-jackson.

**Closed as completed by stickfigure** 2018-11-05 17:49 UTC

**Comment by bseiller** [comment] 2019-07-31 15:38
For everybody that has this problem there is - starting with Jackson 2.8 - an easier workaround than described above in https://github.com/jsog/jsog-jackson/issues/12#issuecomment-316906145 by f0def to get the properties/tokens "@id" and "@ref" ignored.
Depending on where you want to define the ignorals you can do either 
```
public class JsogModule extends SimpleModule {
    // ...

    @Override
    public void setupModule(SetupContext context) {
        // ... 
        context.configOverride(Map.class).setIgnorals(JsonIgnoreProperties.Value.forIgnoredProperties(
                new HashSet<String>() {{
                    add("@id");
                    add("@ref");
                }}
        ));
    }
}
```
or 
```
final ObjectMapper mapper = new ObjectMapper();

// ...

mapper.configOverride(Map.class).setIgnorals(JsonIgnoreProperties.Value.forIgnoredProperties(
        new HashSet<String>() {{
            add("@id");
            add("@ref");
        }}
));
```

**Comment by shubham-sapiens** [comment] 2021-10-21 08:25
I am also facing the same issue, for me @id can be a key in map.
Any Quick workarond to resolve this issue ?
